version: '3'
services:
  pytorch:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"
    ports: 
      - 8888:8888
    volumes: 
      - .:/workspace
